Repository adap/flower, pull requests merged in 2021-12, with the labels that each got.

#945 Fix typos in pytorch example
  doc/source/example-pytorch-from-centralized-to-federated.rst
Labels: documentation

#895 Updating FedOpt and subclasses to latest version of the paper
  src/py/flwr/server/strategy/fedadagrad.py
  src/py/flwr/server/strategy/fedadam.py
  src/py/flwr/server/strategy/fedopt.py
  src/py/flwr/server/strategy/fedyogi.py
Labels: enhancement

#948 FAQ page for the documentation
  doc/source/conf.py
  doc/source/faq.rst
  doc/source/index.rst
Labels: documentation

#863 Federated HuggingFace Transformers using Flower
  examples/transformers-pytorch/README.md
  examples/transformers-pytorch/client.py
  examples/transformers-pytorch/pyproject.toml
  examples/transformers-pytorch/run.sh
  examples/transformers-pytorch/server.py
Labels: enhancement

#869 Remove flwr_example and flwr_experimental from packages
  .github/workflows/docs.yml
  .github/workflows/flower.yml
  .github/workflows/flower_ops.yml
  dev/bootstrap.sh
  dev/fnt.sh
  dev/format.sh
  dev/test-baseline.sh
  dev/test-example-pytorch.sh
  dev/test-example-tensorflow.sh
  dev/test-logserver.sh
  dev/test-ops.sh
  doc/source/changelog.rst
  pyproject.toml
Labels: documentation, enhancement
