Repository adap/flower, pull requests merged in 2023-12, with the labels that each got.

#2226 Add FL+XGBoost Baseline
  baselines/hfedxgboost/.gitignore
  baselines/hfedxgboost/LICENSE
  baselines/hfedxgboost/README.md
  baselines/hfedxgboost/hfedxgboost/__init__.py
  baselines/hfedxgboost/hfedxgboost/client.py
  baselines/hfedxgboost/hfedxgboost/conf/Centralized_Baseline.yaml
  baselines/hfedxgboost/hfedxgboost/conf/base.yaml
  baselines/hfedxgboost/hfedxgboost/conf/centralized_basline_all_datasets_paper_config.yaml
  baselines/hfedxgboost/hfedxgboost/conf/clients/YearPredictionMSD_10_clients.yaml
  baselines/hfedxgboost/hfedxgboost/conf/clients/YearPredictionMSD_2_clients.yaml
  baselines/hfedxgboost/hfedxgboost/conf/clients/YearPredictionMSD_5_clients.yaml
  baselines/hfedxgboost/hfedxgboost/conf/clients/a9a_10_clients.yaml
  baselines/hfedxgboost/hfedxgboost/conf/clients/a9a_2_clients.yaml
  baselines/hfedxgboost/hfedxgboost/conf/clients/a9a_5_clients.yaml
  baselines/hfedxgboost/hfedxgboost/conf/clients/abalone_10_clients.yaml
  baselines/hfedxgboost/hfedxgboost/conf/clients/abalone_2_clients.yaml
  baselines/hfedxgboost/hfedxgboost/conf/clients/abalone_5_clients.yaml
  baselines/hfedxgboost/hfedxgboost/conf/clients/cod_rna_10_clients.yaml
  baselines/hfedxgboost/hfedxgboost/conf/clients/cod_rna_2_clients.yaml
  baselines/hfedxgboost/hfedxgboost/conf/clients/cod_rna_5_clients.yaml
  baselines/hfedxgboost/hfedxgboost/conf/clients/cpusmall_10_clients.yaml
  baselines/hfedxgboost/hfedxgboost/conf/clients/cpusmall_2_clients.yaml
  baselines/hfedxgboost/hfedxgboost/conf/clients/cpusmall_5_clients.yaml
  baselines/hfedxgboost/hfedxgboost/conf/clients/ijcnn1_10_clients.yaml
  baselines/hfedxgboost/hfedxgboost/conf/clients/ijcnn1_2_clients.yaml
  baselines/hfedxgboost/hfedxgboost/conf/clients/ijcnn1_5_clients.yaml
  baselines/hfedxgboost/hfedxgboost/conf/clients/paper_10_clients.yaml
  baselines/hfedxgboost/hfedxgboost/conf/clients/paper_2_clients.yaml
  baselines/hfedxgboost/hfedxgboost/conf/clients/paper_5_clients.yaml
  baselines/hfedxgboost/hfedxgboost/conf/clients/space_ga_10_clients.yaml
  baselines/hfedxgboost/hfedxgboost/conf/clients/space_ga_2_clients.yaml
  baselines/hfedxgboost/hfedxgboost/conf/clients/space_ga_5_clients.yaml
  baselines/hfedxgboost/hfedxgboost/conf/dataset/YearPredictionMSD.yaml
  baselines/hfedxgboost/hfedxgboost/conf/dataset/a9a.yaml
  baselines/hfedxgboost/hfedxgboost/conf/dataset/abalone.yaml
  baselines/hfedxgboost/hfedxgboost/conf/dataset/cod_rna.yaml
  baselines/hfedxgboost/hfedxgboost/conf/dataset/cpusmall.yaml
  baselines/hfedxgboost/hfedxgboost/conf/dataset/ijcnn1.yaml
  baselines/hfedxgboost/hfedxgboost/conf/dataset/space_ga.yaml
  baselines/hfedxgboost/hfedxgboost/conf/dataset/task/Binary_Classification.yaml
  baselines/hfedxgboost/hfedxgboost/conf/dataset/task/Regression.yaml
  baselines/hfedxgboost/hfedxgboost/conf/wandb/default.yaml
  baselines/hfedxgboost/hfedxgboost/conf/xgboost_params_centralized/YearPredictionMSD_xgboost_centralized.yaml
  baselines/hfedxgboost/hfedxgboost/conf/xgboost_params_centralized/abalone_xgboost_centralized.yaml
  baselines/hfedxgboost/hfedxgboost/conf/xgboost_params_centralized/cpusmall_xgboost_centralized.yaml
  baselines/hfedxgboost/hfedxgboost/conf/xgboost_params_centralized/paper_xgboost_centralized.yaml
  baselines/hfedxgboost/hfedxgboost/dataset.py
  baselines/hfedxgboost/hfedxgboost/dataset_preparation.py
  baselines/hfedxgboost/hfedxgboost/main.py
  baselines/hfedxgboost/hfedxgboost/models.py
  baselines/hfedxgboost/hfedxgboost/server.py
  baselines/hfedxgboost/hfedxgboost/strategy.py
  baselines/hfedxgboost/hfedxgboost/sweep.yaml
  baselines/hfedxgboost/hfedxgboost/utils.py
  baselines/hfedxgboost/pyproject.toml
  baselines/hfedxgboost/results.csv
  baselines/hfedxgboost/results_centralized.csv
  doc/source/ref-changelog.md
Labels: summer-of-reproducibility

#2381 Update simulation examples to use `flwr_datasets`
  doc/source/ref-changelog.md
  examples/simulation-pytorch/README.md
  examples/simulation-pytorch/pyproject.toml
  examples/simulation-pytorch/requirements.txt
  examples/simulation-pytorch/sim.ipynb
  examples/simulation-pytorch/sim.py
  examples/simulation-pytorch/utils.py
  examples/simulation-tensorflow/README.md
  examples/simulation-tensorflow/pyproject.toml
  examples/simulation-tensorflow/requirements.txt
  examples/simulation-tensorflow/sim.ipynb
  examples/simulation-tensorflow/sim.py
Labels: Examples

#2686 Add `NodeState` to `RayClientProxy`
  src/py/flwr/simulation/ray_transport/ray_actor.py
  src/py/flwr/simulation/ray_transport/ray_client_proxy.py
  src/py/flwr/simulation/ray_transport/ray_client_proxy_test.py
Labels: simulation

#2412 Add FedVSSL baseline
  baselines/fedvssl/.gitignore
  baselines/fedvssl/LICENSE
  baselines/fedvssl/README.md
  baselines/fedvssl/_static/FVSSL.png
  baselines/fedvssl/fedvssl/__init__.py
  baselines/fedvssl/fedvssl/client.py
  baselines/fedvssl/fedvssl/conf/base.yaml
  baselines/fedvssl/fedvssl/conf/mmcv_conf/finetuning/model_r3d18.py
  baselines/fedvssl/fedvssl/conf/mmcv_conf/finetuning/r3d_18_ucf101/finetune_ucf101.py
  baselines/fedvssl/fedvssl/conf/mmcv_conf/finetuning/r3d_18_ucf101/test_ucf101.py
  baselines/fedvssl/fedvssl/conf/mmcv_conf/finetuning/runtime_ucf101.py
  baselines/fedvssl/fedvssl/conf/mmcv_conf/pretraining/pretraining_runtime_kinetics.py
  baselines/fedvssl/fedvssl/conf/mmcv_conf/pretraining/pretraining_runtime_ucf.py
  baselines/fedvssl/fedvssl/conf/mmcv_conf/pretraining/r3d_18_kinetics/pretraining_for_kinetics.py
  baselines/fedvssl/fedvssl/conf/mmcv_conf/pretraining/r3d_18_ucf101/pretraining_for_ucf.py
  baselines/fedvssl/fedvssl/data_partitioning_k400.py
  baselines/fedvssl/fedvssl/data_partitioning_ucf.py
  baselines/fedvssl/fedvssl/dataset.py
  baselines/fedvssl/fedvssl/dataset_convert_to_json.py
  baselines/fedvssl/fedvssl/dataset_preparation.py
  baselines/fedvssl/fedvssl/finetune_preprocess.py
  baselines/fedvssl/fedvssl/main.py
  baselines/fedvssl/fedvssl/models.py
  baselines/fedvssl/fedvssl/server.py
  baselines/fedvssl/fedvssl/strategy.py
  baselines/fedvssl/fedvssl/utils.py
  baselines/fedvssl/pyproject.toml
  doc/source/ref-changelog.md
Labels: summer-of-reproducibility

#2439 HeteroFL baseline
  baselines/heterofl/LICENSE
  baselines/heterofl/README.md
  baselines/heterofl/heterofl/__init__.py
  baselines/heterofl/heterofl/client.py
  baselines/heterofl/heterofl/client_manager_heterofl.py
  baselines/heterofl/heterofl/conf/base.yaml
  baselines/heterofl/heterofl/conf/fedavg.yaml
  baselines/heterofl/heterofl/dataset.py
  baselines/heterofl/heterofl/dataset_preparation.py
  baselines/heterofl/heterofl/datasets/__init__.py
  baselines/heterofl/heterofl/datasets/cifar.py
  baselines/heterofl/heterofl/datasets/mnist.py
  baselines/heterofl/heterofl/datasets/utils.py
  baselines/heterofl/heterofl/main.py
  baselines/heterofl/heterofl/model_properties.py
  baselines/heterofl/heterofl/models.py
  baselines/heterofl/heterofl/server.py
  baselines/heterofl/heterofl/strategy.py
  baselines/heterofl/heterofl/utils.py
  baselines/heterofl/pyproject.toml
  doc/source/ref-changelog.md
Labels: summer-of-reproducibility

#2724 Retire `MXNet` examples
  README.md
  doc/source/ref-changelog.md
  doc/source/tutorial-quickstart-mxnet.rst
  examples/mxnet-from-centralized-to-federated/README.md
  examples/mxnet-from-centralized-to-federated/pyproject.toml
  examples/mxnet-from-centralized-to-federated/requirements.txt
  examples/quickstart-mxnet/README.md
  examples/quickstart-mxnet/pyproject.toml
  examples/quickstart-mxnet/requirements.txt
Labels: Examples

#2246 Add FedAvgM baseline
  baselines/fedavgm/LICENSE
  baselines/fedavgm/README.md
  baselines/fedavgm/_static/Comparison_CNN_vs_TF_v1_x_Example_for_CIFAR_10.ipynb
  baselines/fedavgm/_static/Figure6_cifar10_num-rounds=1000_concentration=1.png
  baselines/fedavgm/_static/concentration_cifar10.png
  baselines/fedavgm/_static/concentration_cifar10_v2.png
  baselines/fedavgm/_static/custom-fedavgm_vs_fedavgm_rounds=1000_fmnist.png
  baselines/fedavgm/_static/fedavgm_vs_fedavg_rounds=10000_cifar10.png
  baselines/fedavgm/_static/fedavgm_vs_fedavg_rounds=10000_cifar10_w_1e-9.png
  baselines/fedavgm/_static/fedavgm_vs_fedavg_rounds=1000_fmnist.png
  baselines/fedavgm/conf-colab.sh
  baselines/fedavgm/fedavgm/__init__.py
  baselines/fedavgm/fedavgm/client.py
  baselines/fedavgm/fedavgm/common.py
  baselines/fedavgm/fedavgm/conf/base.yaml
  baselines/fedavgm/fedavgm/conf/dataset/cifar10.yaml
  baselines/fedavgm/fedavgm/conf/dataset/fmnist.yaml
  baselines/fedavgm/fedavgm/conf/model/cnn.yaml
  baselines/fedavgm/fedavgm/conf/model/tf_example.yaml
  baselines/fedavgm/fedavgm/conf/strategy/custom-fedavgm.yaml
  baselines/fedavgm/fedavgm/conf/strategy/fedavg.yaml
  baselines/fedavgm/fedavgm/conf/strategy/fedavgm.yaml
  baselines/fedavgm/fedavgm/dataset.py
  baselines/fedavgm/fedavgm/dataset_preparation.py
  baselines/fedavgm/fedavgm/main.py
  baselines/fedavgm/fedavgm/models.py
  baselines/fedavgm/fedavgm/server.py
  baselines/fedavgm/fedavgm/strategy.py
  baselines/fedavgm/fedavgm/utils.py
  baselines/fedavgm/pyproject.toml
  doc/source/ref-changelog.md
Labels: summer-of-reproducibility
