Repository adap/flower, pull requests merged in 2023-10, with the labels that each got.

#2384 Update `embedded_devices` example
  doc/source/ref-changelog.md
  examples/embedded-devices/Dockerfile
  examples/embedded-devices/README.md
  examples/embedded-devices/_static/diagram.png
  examples/embedded-devices/_static/rpi_imager.png
  examples/embedded-devices/base_images/README.md
  examples/embedded-devices/base_images/cpu/Dockerfile
  examples/embedded-devices/base_images/cpu/build.sh
  examples/embedded-devices/base_images/gpu/Dockerfile
  examples/embedded-devices/base_images/gpu/build.sh
  examples/embedded-devices/build_image.sh
  examples/embedded-devices/build_jetson_flower_client.sh
  examples/embedded-devices/client.py
  examples/embedded-devices/client_pytorch.py
  examples/embedded-devices/client_tf.py
  examples/embedded-devices/requirements.txt
  examples/embedded-devices/requirements_pytorch.txt
  examples/embedded-devices/requirements_tf.txt
  examples/embedded-devices/run_jetson.sh
  examples/embedded-devices/run_pi.sh
  examples/embedded-devices/server.py
  examples/embedded-devices/utils.py
Labels: Examples

#2230 Add DASHA baseline
  baselines/dasha/LICENSE
  baselines/dasha/README.md
  baselines/dasha/_static/plot.png
  baselines/dasha/_static/plot_nn.png
  baselines/dasha/dasha/__init__.py
  baselines/dasha/dasha/client.py
  baselines/dasha/dasha/compressors.py
  baselines/dasha/dasha/conf/base.yaml
  baselines/dasha/dasha/conf/dataset/cifar10.yaml
  baselines/dasha/dasha/conf/dataset/libsvm.yaml
  baselines/dasha/dasha/conf/method/dasha.yaml
  baselines/dasha/dasha/conf/method/marina.yaml
  baselines/dasha/dasha/conf/method/stochastic_dasha.yaml
  baselines/dasha/dasha/conf/method/stochastic_marina.yaml
  baselines/dasha/dasha/conf/model/linear_net_with_non_convex_loss.yaml
  baselines/dasha/dasha/conf/model/resnet_18_with_logistic_loss.yaml
  baselines/dasha/dasha/dataset.py
  baselines/dasha/dasha/dataset_preparation.py
  baselines/dasha/dasha/main.py
  baselines/dasha/dasha/models.py
  baselines/dasha/dasha/plot.py
  baselines/dasha/dasha/resnet.py
  baselines/dasha/dasha/server.py
  baselines/dasha/dasha/strategy.py
  baselines/dasha/dasha/tests/datasets/mushrooms_train
  baselines/dasha/dasha/tests/test_clients.py
  baselines/dasha/dasha/tests/test_compressors.py
  baselines/dasha/dasha/tests/test_dasha_baseline.py
  baselines/dasha/dasha/tests/test_datasets.py
  baselines/dasha/dasha/tests/test_models.py
  baselines/dasha/dasha/utils.py
  baselines/dasha/pyproject.toml
Labels: summer-of-reproducibility

#2390 Unify client types
  doc/source/ref-changelog.md
  src/py/flwr/client/__init__.py
  src/py/flwr/client/app.py
  src/py/flwr/client/app_test.py
  src/py/flwr/client/message_handler/message_handler.py
  src/py/flwr/client/numpy_client_wrapper.py
  src/py/flwr/client/typing.py
  src/py/flwr/simulation/app.py
  src/py/flwr/simulation/ray_transport/ray_actor.py
  src/py/flwr/simulation/ray_transport/ray_client_proxy.py
  src/py/flwr/simulation/ray_transport/ray_client_proxy_test.py
  src/py/flwr/simulation/ray_transport/utils.py
Labels: enhancement

#2400 Add table of baselines to docs
  baselines/doc/source/index.rst
  dev/build-baseline-docs.sh
  doc/source/ref-changelog.md
Labels: documentation

#2438 Fedmeta
  baselines/fedmeta/LICENSE
  baselines/fedmeta/README.md
  baselines/fedmeta/_static/femnist_result_graph.png
  baselines/fedmeta/_static/shakespeare_result_graph.png
  baselines/fedmeta/fedmeta/__init__.py
  baselines/fedmeta/fedmeta/client.py
  baselines/fedmeta/fedmeta/conf/algo/fedavg.yaml
  baselines/fedmeta/fedmeta/conf/algo/fedavg_meta.yaml
  baselines/fedmeta/fedmeta/conf/algo/fedmeta_maml.yaml
  baselines/fedmeta/fedmeta/conf/algo/fedmeta_meta_sgd.yaml
  baselines/fedmeta/fedmeta/conf/config.yaml
  baselines/fedmeta/fedmeta/conf/data/femnist.yaml
  baselines/fedmeta/fedmeta/conf/data/shakespeare.yaml
  baselines/fedmeta/fedmeta/dataset.py
  baselines/fedmeta/fedmeta/dataset_preparation.py
  baselines/fedmeta/fedmeta/fedmeta_client_manager.py
  baselines/fedmeta/fedmeta/main.py
  baselines/fedmeta/fedmeta/models.py
  baselines/fedmeta/fedmeta/server.py
  baselines/fedmeta/fedmeta/strategy.py
  baselines/fedmeta/fedmeta/utils.py
  baselines/fedmeta/pyproject.toml
  doc/source/ref-changelog.md
Labels: summer-of-reproducibility

#2526 Update `embedded_devices` example
  doc/source/ref-changelog.md
  examples/embedded-devices/README.md
Labels: Examples

#2431 Add FjORD baseline
  baselines/fjord/.gitignore
  baselines/fjord/LICENSE
  baselines/fjord/README.md
  baselines/fjord/_static/resnet18_cifar10_500_global_rounds_acc_pvalues.png
  baselines/fjord/_static/resnet18_cifar10_fjord_convergence.png
  baselines/fjord/_static/resnet18_cifar10_fjord_kd_convergence.png
  baselines/fjord/fjord/__init__.py
  baselines/fjord/fjord/client.py
  baselines/fjord/fjord/conf/__init__.py
  baselines/fjord/fjord/conf/common.yaml
  baselines/fjord/fjord/conf/config.yaml
  baselines/fjord/fjord/conf/train_mode/fjord.yaml
  baselines/fjord/fjord/conf/train_mode/fjord_kd.yaml
  baselines/fjord/fjord/dataset.py
  baselines/fjord/fjord/dataset_preparation.py
  baselines/fjord/fjord/main.py
  baselines/fjord/fjord/models.py
  baselines/fjord/fjord/od/__init__.py
  baselines/fjord/fjord/od/layers/__init__.py
  baselines/fjord/fjord/od/layers/batch_norm.py
  baselines/fjord/fjord/od/layers/conv.py
  baselines/fjord/fjord/od/layers/linear.py
  baselines/fjord/fjord/od/layers/utils.py
  baselines/fjord/fjord/od/models/__init__.py
  baselines/fjord/fjord/od/models/utils.py
  baselines/fjord/fjord/od/samplers/__init__.py
  baselines/fjord/fjord/od/samplers/base_sampler.py
  baselines/fjord/fjord/od/samplers/fixed_od.py
  baselines/fjord/fjord/server.py
  baselines/fjord/fjord/strategy.py
  baselines/fjord/fjord/utils.py
  baselines/fjord/fjord/utils/__init__.py
  baselines/fjord/fjord/utils/logger.py
  baselines/fjord/fjord/utils/utils.py
  baselines/fjord/notebooks/visualise.ipynb
  baselines/fjord/pyproject.toml
  baselines/fjord/requirements.txt
  baselines/fjord/scripts/run.sh
  baselines/fjord/setup.py
  doc/source/ref-changelog.md
Labels: summer-of-reproducibility

#2421 Add MOON baseline
  baselines/moon/LICENSE
  baselines/moon/README.md
  baselines/moon/_static/cifar100_50clients_moon_fedprox.png
  baselines/moon/_static/cifar100_moon_fedprox.png
  baselines/moon/_static/cifar10_moon_fedprox.png
  baselines/moon/moon/__init__.py
  baselines/moon/moon/client.py
  baselines/moon/moon/conf/base.yaml
  baselines/moon/moon/conf/cifar10.yaml
  baselines/moon/moon/conf/cifar100.yaml
  baselines/moon/moon/conf/cifar100_100clients.yaml
  baselines/moon/moon/conf/cifar100_50clients.yaml
  baselines/moon/moon/conf/cifar100_50clients_fedprox.yaml
  baselines/moon/moon/conf/cifar100_fedprox.yaml
  baselines/moon/moon/conf/cifar10_fedprox.yaml
  baselines/moon/moon/dataset.py
  baselines/moon/moon/dataset_preparation.py
  baselines/moon/moon/main.py
  baselines/moon/moon/models.py
  baselines/moon/moon/server.py
  baselines/moon/moon/strategy.py
  baselines/moon/moon/utils.py
  baselines/moon/pyproject.toml
  doc/source/ref-changelog.md
Labels: summer-of-reproducibility

#2295 Add DepthFL baseline
  baselines/depthfl/.gitignore
  baselines/depthfl/LICENSE
  baselines/depthfl/README.md
  baselines/depthfl/depthfl/__init__.py
  baselines/depthfl/depthfl/client.py
  baselines/depthfl/depthfl/conf/config.yaml
  baselines/depthfl/depthfl/conf/heterofl.yaml
  baselines/depthfl/depthfl/dataset.py
  baselines/depthfl/depthfl/dataset_preparation.py
  baselines/depthfl/depthfl/main.py
  baselines/depthfl/depthfl/models.py
  baselines/depthfl/depthfl/resnet.py
  baselines/depthfl/depthfl/resnet_hetero.py
  baselines/depthfl/depthfl/server.py
  baselines/depthfl/depthfl/strategy.py
  baselines/depthfl/depthfl/strategy_hetero.py
  baselines/depthfl/depthfl/utils.py
  baselines/depthfl/pyproject.toml
  doc/source/ref-changelog.md
Labels: summer-of-reproducibility
