Repository adap/flower, pull requests merged in 2024-08, with the labels that each got.

#3918 refactor(examples) Update `quickstart-pytorch` example
  examples/quickstart-pytorch/README.md
  examples/quickstart-pytorch/client.py
  examples/quickstart-pytorch/pyproject.toml
  examples/quickstart-pytorch/pytorchexample/__init__.py
  examples/quickstart-pytorch/pytorchexample/client_app.py
  examples/quickstart-pytorch/pytorchexample/server_app.py
  examples/quickstart-pytorch/pytorchexample/task.py
  examples/quickstart-pytorch/server.py
Labels: Examples

#3919 refactor(examples) Update `quickstart-tensorflow` example
  examples/quickstart-tensorflow/README.md
  examples/quickstart-tensorflow/client.py
  examples/quickstart-tensorflow/pyproject.toml
  examples/quickstart-tensorflow/server.py
  examples/quickstart-tensorflow/tfexample/__init__.py
  examples/quickstart-tensorflow/tfexample/client_app.py
  examples/quickstart-tensorflow/tfexample/server_app.py
  examples/quickstart-tensorflow/tfexample/task.py
Labels: Examples

#3765 docs(*:skip) Update Flower example using Fastai
  examples/quickstart-fastai/.gitignore
  examples/quickstart-fastai/README.md
  examples/quickstart-fastai/client.py
  examples/quickstart-fastai/fastai_example/__init__.py
  examples/quickstart-fastai/fastai_example/client_app.py
  examples/quickstart-fastai/fastai_example/server_app.py
  examples/quickstart-fastai/fastai_example/task.py
  examples/quickstart-fastai/pyproject.toml
  examples/quickstart-fastai/requirements.txt
  examples/quickstart-fastai/run.sh
  examples/quickstart-fastai/server.py
Labels: Examples

#3758 refactor(examples) Update PyTorch Lightning quickstart example
  examples/quickstart-pytorch-lightning/.gitignore
  examples/quickstart-pytorch-lightning/README.md
  examples/quickstart-pytorch-lightning/client.py
  examples/quickstart-pytorch-lightning/pyproject.toml
  examples/quickstart-pytorch-lightning/pytorchlightning_example/__init__.py
  examples/quickstart-pytorch-lightning/pytorchlightning_example/client_app.py
  examples/quickstart-pytorch-lightning/pytorchlightning_example/server_app.py
  examples/quickstart-pytorch-lightning/pytorchlightning_example/task.py
  examples/quickstart-pytorch-lightning/requirements.txt
  examples/quickstart-pytorch-lightning/run.sh
  examples/quickstart-pytorch-lightning/server.py
Labels: Examples

#3833 refactor(examples) Update secure aggregation example
  examples/app-secure-aggregation/README.md
  examples/app-secure-aggregation/client.py
  examples/app-secure-aggregation/pyproject.toml
  examples/app-secure-aggregation/requirements.txt
  examples/app-secure-aggregation/run.sh
  examples/app-secure-aggregation/server.py
  examples/flower-secure-aggregation/README.md
  examples/flower-secure-aggregation/pyproject.toml
  examples/flower-secure-aggregation/secaggexample/__init__.py
  examples/flower-secure-aggregation/secaggexample/client_app.py
  examples/flower-secure-aggregation/secaggexample/server_app.py
  examples/flower-secure-aggregation/secaggexample/task.py
  examples/flower-secure-aggregation/secaggexample/workflow_with_log.py
Labels: Examples

#3967 feat(datasets) Add tests for iris dataset
  datasets/flwr_datasets/federated_dataset_test.py
  datasets/flwr_datasets/utils.py
Labels: flwr-dataset

#3893 refactor(examples) Refactor quickstart-sklearn-tabular to use the new Flower
  examples/quickstart-sklearn-tabular/README.md
  examples/quickstart-sklearn-tabular/client.py
  examples/quickstart-sklearn-tabular/pyproject.toml
  examples/quickstart-sklearn-tabular/requirements.txt
  examples/quickstart-sklearn-tabular/run.sh
  examples/quickstart-sklearn-tabular/server.py
  examples/quickstart-sklearn-tabular/sklearnexample/__init__.py
  examples/quickstart-sklearn-tabular/sklearnexample/client_app.py
  examples/quickstart-sklearn-tabular/sklearnexample/server_app.py
  examples/quickstart-sklearn-tabular/sklearnexample/task.py
  examples/quickstart-sklearn-tabular/utils.py
Labels: Examples

#3925 docs(examples) Update quickstart tutorial for PyTorch
  doc/source/tutorial-quickstart-mlx.rst
  doc/source/tutorial-quickstart-pytorch.rst
Labels: documentation

#3777 refactor(examples) Update Flower example using `scikit-learn`
  examples/sklearn-logreg-mnist/README.md
  examples/sklearn-logreg-mnist/client.py
  examples/sklearn-logreg-mnist/pyproject.toml
  examples/sklearn-logreg-mnist/requirements.txt
  examples/sklearn-logreg-mnist/run.sh
  examples/sklearn-logreg-mnist/server.py
  examples/sklearn-logreg-mnist/sklearnexample/__init__.py
  examples/sklearn-logreg-mnist/sklearnexample/client_app.py
  examples/sklearn-logreg-mnist/sklearnexample/server_app.py
  examples/sklearn-logreg-mnist/sklearnexample/task.py
  examples/sklearn-logreg-mnist/utils.py
Labels: Examples

#3946 feat(framework) Add `get_fab` func to connection
  src/py/flwr/client/app.py
  src/py/flwr/client/grpc_adapter_client/connection.py
  src/py/flwr/client/grpc_client/connection.py
  src/py/flwr/client/grpc_client/connection_test.py
  src/py/flwr/client/grpc_rere_client/client_interceptor_test.py
  src/py/flwr/client/grpc_rere_client/connection.py
  src/py/flwr/client/rest_client/connection.py
Labels: FAB delivery

#3874 refactor(examples) Update Flower example for variational autoencoder with PyTorch
  examples/pytorch-federated-variational-autoencoder/.gitignore
  examples/pytorch-federated-variational-autoencoder/README.md
  examples/pytorch-federated-variational-autoencoder/client.py
  examples/pytorch-federated-variational-autoencoder/fedvaeexample/__init__.py
  examples/pytorch-federated-variational-autoencoder/fedvaeexample/client_app.py
  examples/pytorch-federated-variational-autoencoder/fedvaeexample/server_app.py
  examples/pytorch-federated-variational-autoencoder/fedvaeexample/task.py
  examples/pytorch-federated-variational-autoencoder/models.py
  examples/pytorch-federated-variational-autoencoder/pyproject.toml
  examples/pytorch-federated-variational-autoencoder/requirements.txt
  examples/pytorch-federated-variational-autoencoder/server.py
Labels: Examples

#3945 feat(framework) Add FAB serde functions
  src/py/flwr/common/serde.py
Labels: FAB delivery

#4017 ci(framework) Add tests for FAB serde functions
  src/py/flwr/common/serde_test.py
Labels: FAB delivery

#3999 feat(framework) Add Ffs factory
  src/py/flwr/server/superlink/ffs/ffs_factory.py
  src/py/flwr/server/superlink/ffs/ffs_factory_test.py
Labels: FAB delivery

#4011 refactor(framework) Make fuse_dicts public for FAB delivery
  src/py/flwr/common/config.py
  src/py/flwr/common/config_test.py
Labels: FAB delivery

#4003 feat(framework:skip) Replace bytes with FAB in exec proto
  src/proto/flwr/proto/exec.proto
  src/py/flwr/cli/run/run.py
  src/py/flwr/proto/exec_pb2.py
  src/py/flwr/proto/exec_pb2.pyi
  src/py/flwr/superexec/exec_servicer.py
  src/py/flwr/superexec/exec_servicer_test.py
Labels: FAB delivery

#4006 feat(framework) Add `fab_hash` to Run
  src/py/flwr/client/app.py
  src/py/flwr/client/grpc_rere_client/connection.py
  src/py/flwr/client/rest_client/connection.py
  src/py/flwr/common/serde.py
  src/py/flwr/common/serde_test.py
  src/py/flwr/common/typing.py
  src/py/flwr/server/app.py
  src/py/flwr/server/driver/grpc_driver.py
  src/py/flwr/server/driver/inmemory_driver_test.py
  src/py/flwr/server/superlink/driver/driver_grpc.py
  src/py/flwr/server/superlink/driver/driver_servicer.py
  src/py/flwr/server/superlink/fleet/grpc_rere/server_interceptor_test.py
  src/py/flwr/server/superlink/fleet/vce/vce_api_test.py
  src/py/flwr/server/superlink/state/in_memory_state.py
  src/py/flwr/server/superlink/state/sqlite_state.py
  src/py/flwr/server/superlink/state/state.py
  src/py/flwr/server/superlink/state/state_test.py
  src/py/flwr/simulation/run_simulation.py
Labels: FAB delivery

#4027 refactor(framework) Make `ffs.get` return optional
  src/py/flwr/server/superlink/ffs/disk_ffs.py
  src/py/flwr/server/superlink/ffs/ffs.py
  src/py/flwr/server/superlink/ffs/ffs_test.py
Labels: FAB delivery

#4019 refactor(framework) Add `get_fab` implementations for FAB delivery
  src/py/flwr/client/grpc_rere_client/connection.py
  src/py/flwr/client/rest_client/connection.py
  src/py/flwr/server/app.py
  src/py/flwr/server/superlink/driver/driver_servicer.py
  src/py/flwr/server/superlink/fleet/grpc_rere/fleet_servicer.py
  src/py/flwr/server/superlink/fleet/grpc_rere/server_interceptor_test.py
  src/py/flwr/server/superlink/fleet/message_handler/message_handler.py
Labels: FAB delivery

#3852 feat(framework) Add end-to-end FAB delivery
  src/py/flwr/client/app.py
  src/py/flwr/client/supernode/app.py
  src/py/flwr/server/run_serverapp.py
  src/py/flwr/superexec/deployment.py
Labels: FAB delivery

#4029 fix(framework) Fix end-to-end FAB delivery
  src/py/flwr/cli/config_utils.py
  src/py/flwr/server/superlink/driver/driver_servicer.py
Labels: FAB delivery

#4041 fix(framework:skip) Avoid reinstalling `FAB` if already installed and confirmation is disabled
  src/py/flwr/cli/install.py
Labels: FAB delivery

#4048 refactor(framework:skip) Remove non-public docstrings for `run_simulation`
  src/py/flwr/simulation/run_simulation.py
Labels: simulation

#4021 docs(framework) Add examples to records docstrings
  src/py/flwr/common/record/configsrecord.py
  src/py/flwr/common/record/metricsrecord.py
  src/py/flwr/common/record/parametersrecord.py
  src/py/flwr/common/record/recordset.py
Labels: documentation

#4053 refactor(examples) Update `fl-tabular` example
  examples/fl-tabular/README.md
  examples/fl-tabular/client.py
  examples/fl-tabular/fltabular/__init__.py
  examples/fl-tabular/fltabular/client_app.py
  examples/fl-tabular/fltabular/server_app.py
  examples/fl-tabular/fltabular/task.py
  examples/fl-tabular/pyproject.toml
  examples/fl-tabular/server.py
Labels: Examples

#3988 refactor(framework) Pass `ClientApp` loading function to backend's build
  src/py/flwr/server/superlink/fleet/vce/backend/backend.py
  src/py/flwr/server/superlink/fleet/vce/backend/raybackend.py
  src/py/flwr/server/superlink/fleet/vce/backend/raybackend_test.py
  src/py/flwr/server/superlink/fleet/vce/vce_api.py
Labels: simulation

#4059 feat(framework) Enable configuring the simulation backend via `flwr run`
  src/py/flwr/cli/run/run.py
  src/py/flwr/simulation/run_simulation.py
  src/py/flwr/superexec/simulation.py
Labels: simulation

#4076 docs(framework) Add note to `flower-server-app` CLI ref
  doc/source/ref-api-cli.rst
Labels: documentation

#3754 refactor(examples) Update Flower example using Hugging Face
  examples/quickstart-huggingface/README.md
  examples/quickstart-huggingface/client.py
  examples/quickstart-huggingface/huggingface_example/__init__.py
  examples/quickstart-huggingface/huggingface_example/client_app.py
  examples/quickstart-huggingface/huggingface_example/server_app.py
  examples/quickstart-huggingface/huggingface_example/task.py
  examples/quickstart-huggingface/pyproject.toml
  examples/quickstart-huggingface/requirements.txt
  examples/quickstart-huggingface/run.sh
  examples/quickstart-huggingface/server.py
Labels: Examples

#3934 refactor(examples) Update `quickstart-monai` example
  examples/quickstart-monai/.gitignore
  examples/quickstart-monai/README.md
  examples/quickstart-monai/client.py
  examples/quickstart-monai/data.py
  examples/quickstart-monai/model.py
  examples/quickstart-monai/monaiexample/__init__.py
  examples/quickstart-monai/monaiexample/client_app.py
  examples/quickstart-monai/monaiexample/server_app.py
  examples/quickstart-monai/monaiexample/task.py
  examples/quickstart-monai/pyproject.toml
  examples/quickstart-monai/requirements.txt
  examples/quickstart-monai/run.sh
  examples/quickstart-monai/server.py
Labels: Examples

#4046 refactor(framework) Update FlowerTune LLM example
  README.md
  examples/doc/source/conf.py
  examples/flowertune-llm/README.md
  examples/flowertune-llm/_static/train_loss_smooth.png
  examples/flowertune-llm/flowertune_llm/__init__.py
  examples/flowertune-llm/flowertune_llm/client_app.py
  examples/flowertune-llm/flowertune_llm/dataset.py
  examples/flowertune-llm/flowertune_llm/models.py
  examples/flowertune-llm/flowertune_llm/server_app.py
  examples/flowertune-llm/pyproject.toml
  examples/flowertune-llm/test.py
  examples/llm-flowertune/README.md
  examples/llm-flowertune/app.py
  examples/llm-flowertune/conf/config.yaml
  examples/llm-flowertune/main.py
  examples/llm-flowertune/requirements.txt
  examples/llm-flowertune/utils.py
Labels: Examples

#3995 docs(baselines) Update baselines contribution docs
  baselines/README.md
  baselines/doc/source/how-to-contribute-baselines.rst
  baselines/doc/source/how-to-use-baselines.rst
Labels: documentation
