Repository adap/flower, pull requests merged in 2024-07, with the labels that each got.

#3468 refactor(framework) Introduce double queue mechanism for Simulation Engine
  src/py/flwr/server/superlink/fleet/vce/vce_api.py
Labels: simulation

#3470 refactor(framework) Remove `asyncio` from core Simulation Engine
  src/py/flwr/server/superlink/fleet/vce/vce_api.py
  src/py/flwr/server/superlink/fleet/vce/vce_api_test.py
Labels: simulation

#3764 fix(framework:skip) Pass arguments to run the `ServerApp` explicitly
  src/py/flwr/simulation/run_simulation.py
Labels: simulation

#3469 refactor(framework) Remove `asyncio` from `Backend` definitions
  src/py/flwr/server/superlink/fleet/vce/backend/backend.py
  src/py/flwr/server/superlink/fleet/vce/backend/raybackend.py
  src/py/flwr/server/superlink/fleet/vce/backend/raybackend_test.py
  src/py/flwr/server/superlink/fleet/vce/vce_api.py
  src/py/flwr/server/superlink/fleet/vce/vce_api_test.py
  src/py/flwr/simulation/ray_transport/ray_actor.py
Labels: simulation

#3472 refactor(framework) Stop launching simulation in thread if asyncio loop detected
  src/py/flwr/simulation/run_simulation.py
Labels: simulation

#3295 docs(framework) Update Flower tutorial series to Flower Next (part 1 of 4)
  doc/source/tutorial-series-get-started-with-flower-pytorch.ipynb
Labels: documentation

#3313 docs(framework) Update Flower tutorial series to Flower Next (part 2 of 4)
  doc/source/tutorial-series-use-a-federated-learning-strategy-pytorch.ipynb
Labels: documentation

#3701 refactor(examples) Update `quickstart-mlx` example
  examples/quickstart-mlx/README.md
  examples/quickstart-mlx/client.py
  examples/quickstart-mlx/mlxexample/__init__.py
  examples/quickstart-mlx/mlxexample/client_app.py
  examples/quickstart-mlx/mlxexample/server_app.py
  examples/quickstart-mlx/mlxexample/task.py
  examples/quickstart-mlx/pyproject.toml
  examples/quickstart-mlx/requirements.txt
  examples/quickstart-mlx/run.sh
  examples/quickstart-mlx/server.py
Labels: Examples

#3314 docs(framework) Update Flower tutorial series to Flower Next (part 3 of 4)
  doc/source/tutorial-series-build-a-strategy-from-scratch-pytorch.ipynb
Labels: documentation

#3316 docs(framework) Update Flower tutorial series to Flower Next (part 4 of 4)
  doc/source/tutorial-series-customize-the-client-pytorch.ipynb
Labels: documentation

#2620 feat(baselines) Add `Flanders` baseline
  baselines/flanders/.gitignore
  baselines/flanders/LICENSE
  baselines/flanders/README.md
  baselines/flanders/_static/screenshot-1.png
  baselines/flanders/_static/screenshot-2.png
  baselines/flanders/_static/screenshot-3.png
  baselines/flanders/_static/screenshot-4.png
  baselines/flanders/_static/screenshot-5.png
  baselines/flanders/_static/screenshot-6.png
  baselines/flanders/_static/screenshot-8.png
  baselines/flanders/_static/screenshot.png
  baselines/flanders/flanders/__init__.py
  baselines/flanders/flanders/attacks.py
  baselines/flanders/flanders/client.py
  baselines/flanders/flanders/conf/aggregate_fn/bulyan.yaml
  baselines/flanders/flanders/conf/aggregate_fn/fedavg.yaml
  baselines/flanders/flanders/conf/aggregate_fn/fedmedian.yaml
  baselines/flanders/flanders/conf/aggregate_fn/krum.yaml
  baselines/flanders/flanders/conf/aggregate_fn/trimmedmean.yaml
  baselines/flanders/flanders/conf/base.yaml
  baselines/flanders/flanders/conf/strategy/bulyan.yaml
  baselines/flanders/flanders/conf/strategy/fedavg.yaml
  baselines/flanders/flanders/conf/strategy/fedmedian.yaml
  baselines/flanders/flanders/conf/strategy/flanders.yaml
  baselines/flanders/flanders/conf/strategy/krum.yaml
  baselines/flanders/flanders/conf/strategy/trimmedmean.yaml
  baselines/flanders/flanders/dataset.py
  baselines/flanders/flanders/dataset_preparation.py
  baselines/flanders/flanders/main.py
  baselines/flanders/flanders/models.py
  baselines/flanders/flanders/server.py
  baselines/flanders/flanders/strategy.py
  baselines/flanders/flanders/utils.py
  baselines/flanders/plotting/FLANDERS_results.ipynb
  baselines/flanders/pyproject.toml
  baselines/flanders/run.sh
Labels: new baseline
