Repository adap/flower, pull requests merged in 2025-09, with the labels that each got.

#5789 refactor(examples): Format quickstart-pytorch
  examples/quickstart-pytorch/pytorchexample/client_app.py
  examples/quickstart-pytorch/pytorchexample/server_app.py
  examples/quickstart-pytorch/pytorchexample/task.py
Labels: Maintainer

#5786 docs(framework): Update `quickstart-pytorch` tutorial
  framework/docs/source/tutorial-quickstart-pytorch.rst
Labels: Maintainer

#5790 ci(intelligence): Bump to 0.2.3 (post 0.2.2 release)
  intelligence/docs/source/conf.py
  intelligence/kt/flwr/src/main/java/ai/flower/intelligence/Constants.kt
  intelligence/kt/gradle.properties
  intelligence/swift/src/Constants.swift
  intelligence/ts/examples/browser-extension/package.json
  intelligence/ts/examples/embedding/package.json
  intelligence/ts/examples/encrypted/package.json
  intelligence/ts/examples/hello-world-js/package.json
  intelligence/ts/examples/hello-world-ts/package.json
  intelligence/ts/examples/nextjs-web-chats/package.json
  intelligence/ts/examples/streaming/package.json
  intelligence/ts/examples/web-chat/package.json
  intelligence/ts/package.json
  intelligence/ts/src/constants.ts
  intelligence/ts/src/flowerintelligence.test.ts
Labels: Maintainer

#5793 fix(intelligence): Add `ToolChoice` type export
  intelligence/ts/src/index.ts
Labels: Maintainer

#5791 feat(intelligence): Add Usage to response
  intelligence/ts/examples/tool-calling/src/index.ts
  intelligence/ts/src/engines/remoteEngine/chat.ts
  intelligence/ts/src/engines/remoteEngine/typing.ts
  intelligence/ts/src/index.ts
  intelligence/ts/src/typing.ts
Labels: Maintainer

#5794 feat(framework): Introduce `SERVERAPP_STRATEGY_AGGREGATION_ERROR`
  framework/docs/source/ref-exit-codes/202.rst
  framework/py/flwr/common/exit/exit_code.py
Labels: Maintainer

#5792 feat(framework): Add `--health-server-address` to SuperLink, SuperNode, and SuperExec
  framework/py/flwr/common/grpc.py
  framework/py/flwr/server/app.py
  framework/py/flwr/supercore/cli/flower_superexec.py
  framework/py/flwr/supercore/grpc_health/__init__.py
  framework/py/flwr/supercore/grpc_health/health_server.py
  framework/py/flwr/supercore/grpc_health/simple_health_servicer.py
  framework/py/flwr/supercore/superexec/run_superexec.py
  framework/py/flwr/supernode/cli/flower_supernode.py
  framework/py/flwr/supernode/start_client_internal.py
Labels: Maintainer

#5799 ci(intelligence): Bump to 0.2.4 (post 0.2.3 release)
  intelligence/docs/source/conf.py
  intelligence/kt/flwr/src/main/java/ai/flower/intelligence/Constants.kt
  intelligence/kt/gradle.properties
  intelligence/swift/src/Constants.swift
  intelligence/ts/examples/browser-extension/package.json
  intelligence/ts/examples/embedding/package.json
  intelligence/ts/examples/encrypted/package.json
  intelligence/ts/examples/hello-world-js/package.json
  intelligence/ts/examples/hello-world-ts/package.json
  intelligence/ts/examples/nextjs-web-chats/package.json
  intelligence/ts/examples/streaming/package.json
  intelligence/ts/examples/web-chat/package.json
  intelligence/ts/package.json
  intelligence/ts/src/constants.ts
  intelligence/ts/src/flowerintelligence.test.ts
Labels: Maintainer

#5804 refactor(*:skip): Log `Result` at the end of strategy `start` execution
  examples/app-pytorch/app_pytorch/server_app.py
  examples/quickstart-pytorch/pytorchexample/server_app.py
  framework/docs/source/tutorial-quickstart-pytorch.rst
  framework/py/flwr/cli/new/templates/app/code/server.pytorch_msg_api.py.tpl
  framework/py/flwr/serverapp/strategy/result.py
  framework/py/flwr/serverapp/strategy/strategy.py
Labels: Maintainer

#5807 refactor(framework): Improve comments in `Strategy.start()` method and the string representation of `Result`
  framework/py/flwr/serverapp/strategy/result.py
  framework/py/flwr/serverapp/strategy/strategy.py
Labels: Maintainer

#5811 refactor(framework): Update docker docs to use SuperExec
  framework/docker/clientapp/README.md
  framework/docker/complete/compose.yml
  framework/docker/distributed/client/compose.yml
  framework/docker/distributed/server/compose.yml
  framework/docker/serverapp/README.md
  framework/docs/source/docker/tutorial-quickstart-docker-compose.rst
Labels: Maintainer

#5813 refactor(framework): Allow `None` return for `evaluate-fn` callback
  framework/py/flwr/serverapp/strategy/strategy.py
Labels: Maintainer

#5817 docs(framework): Fix how to design stateful `ClientApp` guide
  framework/docs/source/how-to-design-stateful-clients.rst
Labels: Maintainer

#5820 fix(framework): Avoid confusing CLI prompt when `UNIMPLEMENTED` gRPC status code is detected
  framework/py/flwr/cli/utils.py
  framework/py/flwr/common/constant.py
  framework/py/flwr/superlink/servicer/control/control_servicer.py
Labels: Maintainer

#5816 docs(framework): Update Helm docs for 1.21.0
  framework/docs/source/helm/how-to-deploy-superlink-using-helm.md
  framework/docs/source/helm/how-to-deploy-supernode-using-helm.md
Labels: Maintainer

#5824 refactor(framework): Perform aggregation with `np.asarray` wrapping
  framework/py/flwr/serverapp/strategy/strategy_utils.py
  framework/py/flwr/serverapp/strategy/strategy_utils_tests.py
Labels: Maintainer

#5829 ci(*:skip): Amend code owners for CLI code
  .github/CODEOWNERS
Labels: Maintainer

#5843 ci(framework): Update CI tests to use `flwr ls` when checking for status of a run
  framework/e2e/test_reconnection.sh
  framework/e2e/test_superlink.sh
  framework/e2e/test_windows.sh
Labels: Maintainer

#5830 refactor(examples): Update advanced examples to `Message API`
  examples/advanced-pytorch/README.md
  examples/advanced-pytorch/pyproject.toml
  examples/advanced-pytorch/pytorch_example/client_app.py
  examples/advanced-pytorch/pytorch_example/server_app.py
  examples/advanced-pytorch/pytorch_example/strategy.py
  examples/advanced-pytorch/pytorch_example/task.py
  examples/advanced-tensorflow/README.md
  examples/advanced-tensorflow/certificates/certificate.conf
  examples/advanced-tensorflow/certificates/generate.sh
  examples/advanced-tensorflow/pyproject.toml
  examples/advanced-tensorflow/tensorflow_example/client_app.py
  examples/advanced-tensorflow/tensorflow_example/server_app.py
  examples/advanced-tensorflow/tensorflow_example/strategy.py
Labels: Maintainer

#5865 ci(*:skip): Ensure bootstrapping when examples are changed
  .github/workflows/framework.yml
Labels: Maintainer

#5827 refactor(examples): Update XGBoost quick-start example
  examples/xgboost-quickstart/pyproject.toml
  examples/xgboost-quickstart/xgboost_quickstart/client_app.py
  examples/xgboost-quickstart/xgboost_quickstart/server_app.py
  examples/xgboost-quickstart/xgboost_quickstart/task.py
  framework/py/flwr/serverapp/strategy/__init__.py
  framework/py/flwr/serverapp/strategy/fedxgb_bagging.py
  framework/py/flwr/serverapp/strategy/strategy_utils.py
Labels: Maintainer

#5839 refactor(examples): Migrate `quickstart-fastai` example to `Message API`
  examples/quickstart-fastai/fastai_example/client_app.py
  examples/quickstart-fastai/fastai_example/server_app.py
  examples/quickstart-fastai/fastai_example/task.py
  examples/quickstart-fastai/pyproject.toml
Labels: Maintainer

#5861 docs(framework): Update main tutorial to the `Message API`
  framework/docs/source/tutorial-series-build-a-strategy-from-scratch-pytorch.rst
  framework/docs/source/tutorial-series-customize-the-client-pytorch.rst
  framework/docs/source/tutorial-series-get-started-with-flower-pytorch.rst
  framework/docs/source/tutorial-series-use-a-federated-learning-strategy-pytorch.rst
  framework/docs/source/tutorial-series-what-is-federated-learning.rst
Labels: Maintainer

#5868 refactor(examples): Migrate `quickstart-huggingface` example to `Message` API
  examples/quickstart-huggingface/huggingface_example/client_app.py
  examples/quickstart-huggingface/huggingface_example/server_app.py
  examples/quickstart-huggingface/huggingface_example/task.py
  examples/quickstart-huggingface/pyproject.toml
Labels: Maintainer

#5849 refactor(framework): Label `PyTorch` template based on `NumpyClient` as legacy
  .github/workflows/framework-e2e.yml
  framework/py/flwr/cli/new/new.py
  framework/py/flwr/cli/new/templates/app/code/__init__.pytorch_legacy_api.py.tpl
  framework/py/flwr/cli/new/templates/app/code/client.pytorch.py.tpl
  framework/py/flwr/cli/new/templates/app/code/client.pytorch_legacy_api.py.tpl
  framework/py/flwr/cli/new/templates/app/code/client.pytorch_msg_api.py.tpl
  framework/py/flwr/cli/new/templates/app/code/server.pytorch.py.tpl
  framework/py/flwr/cli/new/templates/app/code/server.pytorch_legacy_api.py.tpl
  framework/py/flwr/cli/new/templates/app/code/server.pytorch_msg_api.py.tpl
  framework/py/flwr/cli/new/templates/app/code/task.pytorch.py.tpl
  framework/py/flwr/cli/new/templates/app/code/task.pytorch_legacy_api.py.tpl
  framework/py/flwr/cli/new/templates/app/pyproject.pytorch.toml.tpl
  framework/py/flwr/cli/new/templates/app/pyproject.pytorch_legacy_api.toml.tpl
Labels: Maintainer

#5850 feat(framework): Add `FedAvgM`, `FedMedian`, and `FedTrimmedAvg` strategies
  framework/py/flwr/serverapp/strategy/__init__.py
  framework/py/flwr/serverapp/strategy/fedavg.py
  framework/py/flwr/serverapp/strategy/fedavgm.py
  framework/py/flwr/serverapp/strategy/fedavgm_test.py
  framework/py/flwr/serverapp/strategy/fedmedian.py
  framework/py/flwr/serverapp/strategy/fedmedian_test.py
  framework/py/flwr/serverapp/strategy/fedtrimmedavg.py
  framework/py/flwr/serverapp/strategy/fedtrimmedavg_test.py
  framework/py/flwr/serverapp/strategy/strategy_utils_tests.py
Labels: Maintainer

#5873 refactor(examples): Format examples
  examples/flower-authentication/authexample/client_app.py
  examples/flower-authentication/authexample/server_app.py
  examples/quickstart-fastai/fastai_example/client_app.py
  examples/quickstart-huggingface/huggingface_example/task.py
Labels: Maintainer

#5874 ci(examples): Fail CI if any `isort` job fails
  dev/test.sh
Labels: Maintainer

#5870 docs(framework): Remove tutorial notebooks and update links in `README.md`
  README.md
  framework/README.md
  framework/dev/format.sh
  framework/docs/source/index.rst
  framework/docs/source/notebooks/index.rst
  framework/docs/source/notebooks/tutorial-series-build-a-strategy-from-scratch-pytorch.ipynb
  framework/docs/source/notebooks/tutorial-series-customize-the-client-pytorch.ipynb
  framework/docs/source/notebooks/tutorial-series-get-started-with-flower-pytorch.ipynb
  framework/docs/source/notebooks/tutorial-series-use-a-federated-learning-strategy-pytorch.ipynb
Labels: Maintainer

#5869 feat(examples): Update JAX example
  examples/quickstart-jax/jaxexample/client_app.py
  examples/quickstart-jax/jaxexample/server_app.py
  examples/quickstart-jax/jaxexample/task.py
  examples/quickstart-jax/pyproject.toml
Labels: Maintainer

#5879 feat(examples): Update custom mods example
  examples/custom-mods/README.md
  examples/custom-mods/custom_mods/client_app.py
  examples/custom-mods/custom_mods/mods.py
  examples/custom-mods/custom_mods/server_app.py
  examples/custom-mods/custom_mods/task.py
  examples/custom-mods/pyproject.toml
Labels: Maintainer

#5888 refactor(examples): Add saving of final model for Hugging Face quickstart
  examples/quickstart-huggingface/huggingface_example/server_app.py
Labels: Maintainer

#5863 feat(framework): Introduce `flwr pull`
  framework/proto/flwr/proto/control.proto
  framework/py/flwr/cli/app.py
  framework/py/flwr/cli/pull.py
  framework/py/flwr/cli/utils.py
  framework/py/flwr/common/constant.py
  framework/py/flwr/proto/control_pb2.py
  framework/py/flwr/proto/control_pb2.pyi
  framework/py/flwr/proto/control_pb2_grpc.py
  framework/py/flwr/proto/control_pb2_grpc.pyi
  framework/py/flwr/server/app.py
  framework/py/flwr/superlink/artifact_provider/__init__.py
  framework/py/flwr/superlink/artifact_provider/artifact_provider.py
  framework/py/flwr/superlink/servicer/control/control_grpc.py
  framework/py/flwr/superlink/servicer/control/control_servicer.py
Labels: Maintainer

#5892 refactor(examples): Update FL tabular example
  examples/fl-tabular/README.md
  examples/fl-tabular/fltabular/client_app.py
  examples/fl-tabular/fltabular/server_app.py
  examples/fl-tabular/fltabular/task.py
  examples/fl-tabular/pyproject.toml
Labels: Contributor

#5883 refactor(framework): Update FlowerTune template
  framework/py/flwr/cli/new/new.py
  framework/py/flwr/cli/new/templates/app/README.flowertune.md.tpl
  framework/py/flwr/cli/new/templates/app/code/flwr_tune/client_app.py.tpl
  framework/py/flwr/cli/new/templates/app/code/flwr_tune/models.py.tpl
  framework/py/flwr/cli/new/templates/app/code/flwr_tune/server_app.py.tpl
  framework/py/flwr/cli/new/templates/app/code/flwr_tune/strategy.py.tpl
  framework/py/flwr/cli/new/templates/app/pyproject.flowertune.toml.tpl
Labels: Contributor

#5890 refactor(framework): Pass `Context` received from SuperLink to `ServerApp` in `flwr-simulation`
  framework/py/flwr/simulation/app.py
  framework/py/flwr/simulation/run_simulation.py
Labels: Maintainer

#5895 refactor(framework): Update `quickstart-tensorflow` tutorial to Message API
  framework/docs/source/tutorial-quickstart-tensorflow.rst
Labels: Maintainer

#5862 docs(framework): Update `MLX` quickstart tutorials and fix that for `PyTorch`
  framework/docs/source/tutorial-quickstart-mlx.rst
  framework/docs/source/tutorial-quickstart-pytorch.rst
Labels: Maintainer

#5898 docs(framework): Update quickstart PyTorch Lightning tutorial
  framework/docs/source/tutorial-quickstart-pytorch-lightning.rst
Labels: Maintainer

#5909 feat(framework): Add `TypedDict.copy` method
  framework/py/flwr/common/record/recorddict_test.py
  framework/py/flwr/common/record/typeddict.py
Labels: Maintainer

#5894 refactor(framework): Migrate `Krum` strategy to `Message API`
  framework/py/flwr/serverapp/strategy/__init__.py
  framework/py/flwr/serverapp/strategy/krum.py
  framework/py/flwr/serverapp/strategy/krum_test.py
Labels: Maintainer

#5905 feat(framework): Add Message-based adaptive clipping strategies
  framework/py/flwr/clientapp/mod/__init__.py
  framework/py/flwr/clientapp/mod/centraldp_mods.py
  framework/py/flwr/serverapp/dp_fixed_clipping.py
  framework/py/flwr/serverapp/strategy/__init__.py
  framework/py/flwr/serverapp/strategy/dp_adaptive_clipping.py
  framework/py/flwr/serverapp/strategy/dp_fixed_clipping.py
Labels: Maintainer

#5887 refactor(examples): Migrate `quickstart-monai` to Message API
  examples/quickstart-monai/monaiexample/client_app.py
  examples/quickstart-monai/monaiexample/server_app.py
  examples/quickstart-monai/monaiexample/task.py
  examples/quickstart-monai/pyproject.toml
Labels: Maintainer

#5914 refactor(framework): Use `│` instead of `|` to ensure consistency and make it prettier
  framework/py/flwr/serverapp/strategy/fedavgm.py
  framework/py/flwr/serverapp/strategy/fedprox.py
  framework/py/flwr/serverapp/strategy/fedtrimmedavg.py
  framework/py/flwr/serverapp/strategy/krum.py
Labels: Maintainer

#5897 refactor(framework): Update quickstart-fastai tutorial to Message API
  framework/docs/source/tutorial-quickstart-fastai.rst
Labels: Maintainer

#5912 docs(framework): Update tutorial of how to use built-in Mods
  framework/docs/source/how-to-use-built-in-mods.rst
Labels: Contributor

#5926 Merge to `how-to-use-strategies`
  framework/docs/source/how-to-use-strategies.rst
Labels: Maintainer

#5927 docs(framework): Update how to implement FedBN tutorial
  framework/docs/source/how-to-implement-fedbn.rst
Labels: Contributor

#5919 refactor(framework): Refactor `Krum` strategies
  framework/py/flwr/serverapp/strategy/__init__.py
  framework/py/flwr/serverapp/strategy/krum.py
  framework/py/flwr/serverapp/strategy/multikrum.py
  framework/py/flwr/serverapp/strategy/multikrum_test.py
Labels: Maintainer

#5923 docs(framework): Update `how-to-configure-clients` guide to `Message API`
  framework/docs/source/how-to-configure-clients.rst
Labels: Maintainer

#5921 docs(framework): Update tutorial of how to aggregate eval results
  framework/docs/source/how-to-aggregate-evaluation-results.rst
Labels: Contributor

#5928 docs(framework): Update how to save checkpoints tutorial
  framework/docs/source/how-to-save-and-load-model-checkpoints.rst
Labels: Maintainer

#5924 docs(framework): Update `how-to-design-stateful-clients` guide to the `Message API`
  framework/docs/source/how-to-design-stateful-clients.rst
Labels: Maintainer

#5920 feat(framework): Implement `Bulyan` for Message API
  framework/py/flwr/serverapp/strategy/__init__.py
  framework/py/flwr/serverapp/strategy/bulyan.py
  framework/py/flwr/serverapp/strategy/bulyan_test.py
Labels: Maintainer

#5815 ci(*:skip): Fix `update_version.py` to use the correct latest version and fix patterns
  framework/dev/update_version.py
Labels: Maintainer

#5933 feat(framework): Update changelog for `v1.22.0`
  framework/docs/source/ref-changelog.md
Labels: Maintainer

#5932 ci(*:skip): Bump versions to v1.23.0
  baselines/docs/source/conf.py
  examples/advanced-pytorch/pyproject.toml
  examples/advanced-tensorflow/pyproject.toml
  examples/app-pytorch/pyproject.toml
  examples/custom-metrics/pyproject.toml
  examples/custom-mods/pyproject.toml
  examples/docs/source/conf.py
  examples/embedded-devices/pyproject.toml
  examples/federated-kaplan-meier-fitter/pyproject.toml
  examples/fedrag/pyproject.toml
  examples/fl-dp-sa/pyproject.toml
  examples/fl-tabular/pyproject.toml
  examples/flower-authentication/pyproject.toml
  examples/flower-secure-aggregation/pyproject.toml
  examples/flower-simulation-step-by-step-pytorch/my-awesome-app/pyproject.toml
  examples/flowertune-llm/pyproject.toml
  examples/flowertune-vit/pyproject.toml
  examples/opacus/pyproject.toml
  examples/pytorch-federated-variational-autoencoder/pyproject.toml
  examples/quickstart-catboost/pyproject.toml
  examples/quickstart-fastai/pyproject.toml
  examples/quickstart-huggingface/pyproject.toml
  examples/quickstart-jax/pyproject.toml
  examples/quickstart-lerobot/pyproject.toml
  examples/quickstart-mlx/pyproject.toml
  examples/quickstart-monai/pyproject.toml
  examples/quickstart-pandas/pyproject.toml
  examples/quickstart-pytorch-lightning/pyproject.toml
  examples/quickstart-pytorch/pyproject.toml
  examples/quickstart-sklearn-tabular/pyproject.toml
  examples/quickstart-tensorflow/pyproject.toml
  examples/sklearn-logreg-mnist/pyproject.toml
  examples/tensorflow-privacy/pyproject.toml
  examples/vertical-fl/pyproject.toml
  examples/whisper-federated-finetuning/pyproject.toml
  examples/xgboost-comprehensive/pyproject.toml
  examples/xgboost-quickstart/pyproject.toml
  framework/docker/base/README.md
  framework/docker/complete/compose.yml
  framework/docker/distributed/client/compose.yml
  framework/docker/distributed/server/compose.yml
  framework/docker/superexec/README.md
  framework/docker/superlink/README.md
  framework/docker/supernode/README.md
  framework/docs/source/conf.py
  framework/docs/source/ref-changelog.md
  framework/py/flwr/cli/new/templates/app/pyproject.baseline.toml.tpl
  framework/py/flwr/cli/new/templates/app/pyproject.flowertune.toml.tpl
  framework/py/flwr/cli/new/templates/app/pyproject.huggingface.toml.tpl
  framework/py/flwr/cli/new/templates/app/pyproject.jax.toml.tpl
  framework/py/flwr/cli/new/templates/app/pyproject.mlx.toml.tpl
  framework/py/flwr/cli/new/templates/app/pyproject.numpy.toml.tpl
  framework/py/flwr/cli/new/templates/app/pyproject.pytorch.toml.tpl
  framework/py/flwr/cli/new/templates/app/pyproject.pytorch_legacy_api.toml.tpl
  framework/py/flwr/cli/new/templates/app/pyproject.sklearn.toml.tpl
  framework/py/flwr/cli/new/templates/app/pyproject.tensorflow.toml.tpl
  framework/py/flwr/cli/new/templates/app/pyproject.xgboost.toml.tpl
  framework/pyproject.toml
Labels: Maintainer

#5936 docs(framework:skip): Fix typo in SuperLink image for `1.22.0`
  framework/docker/superlink/README.md
Labels: Maintainer

#5944 feat(framework): Bump `licensecheck` from `2024` to `2025.1.0`
  framework/dev/test.sh
  framework/pyproject.toml
Labels: Maintainer

#5954 refactor(framework): Move `*Auth*Pugin` classes
  framework/py/flwr/cli/auth_plugin/__init__.py
  framework/py/flwr/cli/auth_plugin/auth_plugin.py
  framework/py/flwr/cli/auth_plugin/oidc_cli_plugin.py
  framework/py/flwr/cli/cli_user_auth_interceptor.py
  framework/py/flwr/cli/utils.py
  framework/py/flwr/server/app.py
  framework/py/flwr/superlink/auth_plugin/__init__.py
  framework/py/flwr/superlink/auth_plugin/auth_plugin.py
  framework/py/flwr/superlink/servicer/control/control_grpc.py
  framework/py/flwr/superlink/servicer/control/control_servicer.py
  framework/py/flwr/superlink/servicer/control/control_user_auth_interceptor.py
Labels: Maintainer, Dynamic Add/Remove SuperNodes

#5943 docs(framework): Make dark mode better
  framework/docs/source/_static/custom.css
  framework/docs/source/_static/flower-architecture-basic-architecture-dark.svg
  framework/docs/source/_static/flower-architecture-basic-architecture-light.svg
  framework/docs/source/_static/flower-architecture-basic-architecture.svg
  framework/docs/source/_static/flower-architecture-hub-and-spoke-dark.svg
  framework/docs/source/_static/flower-architecture-hub-and-spoke-light.svg
  framework/docs/source/_static/flower-architecture-multi-run-1-dark.svg
  framework/docs/source/_static/flower-architecture-multi-run-1-light.svg
  framework/docs/source/_static/flower-architecture-multi-run-1.svg
  framework/docs/source/_static/flower-architecture-multi-run-2-dark.svg
  framework/docs/source/_static/flower-architecture-multi-run-2-light.svg
  framework/docs/source/_static/flower-architecture-multi-run-2.svg
  framework/docs/source/_static/flower-architecture-multi-run-dark.svg
  framework/docs/source/_static/flower-architecture-multi-run-light.svg
  framework/docs/source/_static/flower-architecture-multi-run.svg
  framework/docs/source/_static/flower-network-diagram-process-dark.svg
  framework/docs/source/_static/flower-network-diagram-process-light.svg
  framework/docs/source/_static/flower-network-diagram-process.svg
  framework/docs/source/_static/flower-network-diagram-subprocess-dark.svg
  framework/docs/source/_static/flower-network-diagram-subprocess-light.svg
  framework/docs/source/_static/flower-network-diagram-subprocess.svg
  framework/docs/source/_templates/base.html
  framework/docs/source/contributor-ref-secure-aggregation-protocols.rst
  framework/docs/source/explanation-flower-architecture.rst
  framework/docs/source/ref-flower-network-communication.rst
Labels: Maintainer
