Repository adap/flower, pull requests merged in 2025-05, with the labels that each got.

#4941 feat(baselines) Add Floco Baseline
  baselines/floco/.gitignore
  baselines/floco/LICENSE
  baselines/floco/README.md
  baselines/floco/_static/CIFAR10_Dirichlet.png
  baselines/floco/_static/CIFAR10_Fold.png
  baselines/floco/conf/cifar10_dir_fedavg.toml
  baselines/floco/conf/cifar10_dir_floco.toml
  baselines/floco/conf/cifar10_dir_floco_p.toml
  baselines/floco/conf/cifar10_fold_fedavg.toml
  baselines/floco/conf/cifar10_fold_floco.toml
  baselines/floco/conf/cifar10_fold_floco_p.toml
  baselines/floco/floco/__init__.py
  baselines/floco/floco/client_app.py
  baselines/floco/floco/dataset.py
  baselines/floco/floco/model.py
  baselines/floco/floco/partitioners.py
  baselines/floco/floco/plot_results.py
  baselines/floco/floco/server_app.py
  baselines/floco/floco/strategy.py
  baselines/floco/pyproject.toml
  baselines/floco/run.sh
Labels: New Baseline

#5381 feat(framework) Add workflow to label PR as Maintainer or Contributor
  .github/workflows/label-pr-author.yaml
Labels: Maintainer

#5398 refactor(framework) Remove in-process Client execution from SuperNode main loop
  framework/py/flwr/client/start_client_internal.py
  framework/py/flwr/client/supernode/app.py
Labels: Maintainer

#5401 docs(framework) Remove links to deprecated video tutorials
  framework/docs/source/tutorial-quickstart-pytorch.rst
  framework/docs/source/tutorial-quickstart-tensorflow.rst
Labels: Contributor

#5408 refactor(framework) Move SuperNode code to `flwr.supernode` module
  framework/py/flwr/client/supernode/__init__.py
  framework/py/flwr/supernode/app.py
  framework/py/flwr/supernode/start_client_internal.py
  framework/pyproject.toml
Labels: Maintainer

#5409 refactor(framework) Move `flwr.supernode.app` to `flwr.supernode.cli.flower_supernode`
  framework/docs/source/ref-api-cli.rst
  framework/py/flwr/supernode/cli/__init__.py
  framework/py/flwr/supernode/cli/flower_supernode.py
  framework/pyproject.toml
Labels: Contributor

#5410 refactor(framework) Centralize connection code in `start_client_internal.py`
  framework/py/flwr/supernode/start_client_internal.py
Labels: Maintainer

#5411 refactor(framework) Remove unused `try-except` block in SuperNode
  framework/py/flwr/supernode/start_client_internal.py
Labels: Maintainer

#5413 refactor(framework) Move `start_server` to `flwr.compat`
  framework/py/flwr/compat/server/app.py
  framework/py/flwr/server/__init__.py
  framework/py/flwr/server/app.py
Labels: Maintainer

#5388 ci(intelligence) Change to automatic deployment for Kotlin SDK
  intelligence/kt/dev/publish.sh
Labels: Maintainer

#5419 refactor(framework) Remove unused code in `compat.client.app` to facilitate SuperNode refactoring
  framework/py/flwr/compat/client/app.py
Labels: Maintainer

#5421 feat(framework) Add get authorization plugin to SuperLink
  framework/py/flwr/common/constant.py
  framework/py/flwr/server/app.py
Labels: Maintainer

#5429 refactor(framework) Cache `.object_id` and introduce `.is_dirty`
  framework/py/flwr/common/inflatable.py
  framework/py/flwr/common/record/array.py
  framework/py/flwr/common/record/arrayrecord.py
  framework/py/flwr/common/serde.py
Labels: Maintainer

#5432 refactor(framework) Move `message_id` creation out of `LinkState` and use `.object_id` in Deployment
  framework/py/flwr/client/grpc_rere_client/connection.py
  framework/py/flwr/client/message_handler/message_handler.py
  framework/py/flwr/client/message_handler/message_handler_test.py
  framework/py/flwr/server/grid/grpc_grid.py
  framework/py/flwr/server/grid/grpc_grid_test.py
  framework/py/flwr/server/grid/inmemory_grid.py
  framework/py/flwr/server/grid/inmemory_grid_test.py
  framework/py/flwr/server/superlink/fleet/message_handler/message_handler.py
  framework/py/flwr/server/superlink/fleet/vce/vce_api.py
  framework/py/flwr/server/superlink/fleet/vce/vce_api_test.py
  framework/py/flwr/server/superlink/linkstate/in_memory_linkstate.py
  framework/py/flwr/server/superlink/linkstate/linkstate.py
  framework/py/flwr/server/superlink/linkstate/linkstate_test.py
  framework/py/flwr/server/superlink/linkstate/sqlite_linkstate.py
  framework/py/flwr/server/superlink/linkstate/utils.py
  framework/py/flwr/server/superlink/serverappio/serverappio_servicer.py
  framework/py/flwr/server/superlink/serverappio/serverappio_servicer_test.py
  framework/py/flwr/server/utils/validator.py
  framework/py/flwr/server/utils/validator_test.py
  framework/py/flwr/superexec/exec_servicer.py
Labels: Maintainer

#5428 feat(framework) Add test to auth interceptor for authorization protocol
  framework/py/flwr/superexec/exec_user_auth_interceptor_test.py
Labels: Maintainer

#5434 refactor(framework) Enable preregistration of objects in `ObjectStore` via the servicers
  framework/proto/flwr/proto/fleet.proto
  framework/proto/flwr/proto/message.proto
  framework/proto/flwr/proto/serverappio.proto
  framework/py/flwr/common/message.py
  framework/py/flwr/proto/fleet_pb2.py
  framework/py/flwr/proto/fleet_pb2.pyi
  framework/py/flwr/proto/message_pb2.py
  framework/py/flwr/proto/message_pb2.pyi
  framework/py/flwr/proto/serverappio_pb2.py
  framework/py/flwr/proto/serverappio_pb2.pyi
  framework/py/flwr/server/app.py
  framework/py/flwr/server/superlink/fleet/grpc_rere/fleet_servicer.py
  framework/py/flwr/server/superlink/fleet/grpc_rere/fleet_servicer_test.py
  framework/py/flwr/server/superlink/fleet/message_handler/message_handler.py
  framework/py/flwr/server/superlink/fleet/message_handler/message_handler_test.py
  framework/py/flwr/server/superlink/fleet/rest_rere/rest_api.py
  framework/py/flwr/server/superlink/serverappio/serverappio_servicer.py
  framework/py/flwr/server/superlink/serverappio/serverappio_servicer_test.py
  framework/py/flwr/server/superlink/utils.py
Labels: Maintainer

#5440 fix(framework) Add option to label bot PRs as Bot
  .github/workflows/label-pr-author.yaml
Labels: Maintainer

#5443 refactor(framework) Trim unnecessary code in `flwr.supernode.start_client_internal`
  framework/py/flwr/supernode/start_client_internal.py
Labels: Maintainer

#5445 refactor(framework) Update gRPC utils for `InflatableObjects`
  framework/py/flwr/common/inflatable_grpc_utils.py
  framework/py/flwr/common/inflatable_grpc_utils_test.py
Labels: Maintainer

#5446 refactor(framework) Introduce `NoObjectInStoreError`
  framework/py/flwr/supercore/object_store/in_memory_object_store.py
  framework/py/flwr/supercore/object_store/object_store.py
  framework/py/flwr/supercore/object_store/object_store_test.py
Labels: Maintainer

#5374 docs(framework) Update Flower with Deployment Engine Page
  framework/docs/source/how-to-run-flower-with-deployment-engine.rst
Labels: Maintainer
