Repository adap/flower, pull requests merged in 2025-10, with the labels that each got.

#5950 docs(framework): Update `30-minute` Flower tutorial to `Message API`
  examples/flower-in-30-minutes/tutorial.ipynb
Labels: Maintainer

#5963 refactor(examples): Update imports for `quickstar-pandas` example
  examples/quickstart-pandas/pandas_example/client_app.py
  examples/quickstart-pandas/pandas_example/server_app.py
Labels: Maintainer, Migrate to MessageAPI

#5959 fix(framework): Correct superexec docker entrypoint
  framework/docker/complete/compose.yml
  framework/docker/distributed/client/compose.yml
  framework/docker/distributed/server/compose.yml
  framework/docs/source/docker/tutorial-quickstart-docker-compose.rst
Labels: Contributor

#5955 feat(framework): Add `NoOp*Plugin`s
  framework/py/flwr/cli/auth_plugin/__init__.py
  framework/py/flwr/cli/auth_plugin/auth_plugin.py
  framework/py/flwr/cli/auth_plugin/noop_auth_plugin.py
  framework/py/flwr/cli/auth_plugin/oidc_cli_plugin.py
  framework/py/flwr/cli/login/login.py
  framework/py/flwr/common/constant.py
  framework/py/flwr/superlink/auth_plugin/__init__.py
  framework/py/flwr/superlink/auth_plugin/noop_auth_plugin.py
Labels: Maintainer, Dynamic Add/Remove SuperNodes

#5962 feat(framework): Introduce flwr supernode xyz commands
  framework/py/flwr/cli/app.py
  framework/py/flwr/cli/supernode/__init__.py
  framework/py/flwr/cli/supernode/create.py
  framework/py/flwr/cli/supernode/delete.py
  framework/py/flwr/cli/supernode/ls.py
Labels: Maintainer, Dynamic Add/Remove SuperNodes

#5966 refactor(examples): Migrate `whisper` example to `Message API`
  examples/whisper-federated-finetuning/README.md
  examples/whisper-federated-finetuning/pyproject.toml
  examples/whisper-federated-finetuning/whisper_example/client_app.py
  examples/whisper-federated-finetuning/whisper_example/dataset.py
  examples/whisper-federated-finetuning/whisper_example/model.py
  examples/whisper-federated-finetuning/whisper_example/server_app.py
Labels: Maintainer, Migrate to MessageAPI

#5969 break(framework): Rename the yaml key to `authn_type` from `auth_type` and rename user auth to account auth for consistency
  framework/docs/source/_static/flower-network-diagram-process-dark.svg
  framework/docs/source/_static/flower-network-diagram-process-light.svg
  framework/docs/source/_static/flower-network-diagram-subprocess-dark.svg
  framework/docs/source/_static/flower-network-diagram-subprocess-light.svg
  framework/docs/source/conf.py
  framework/docs/source/deploy.rst
  framework/docs/source/helm/how-to-deploy-superlink-using-helm.md
  framework/docs/source/how-to-authenticate-accounts.rst
  framework/docs/source/how-to-authenticate-users.rst
  framework/docs/source/ref-flower-network-communication.rst
  framework/proto/flwr/proto/control.proto
  framework/py/flwr/cli/auth_plugin/__init__.py
  framework/py/flwr/cli/auth_plugin/oidc_cli_plugin.py
  framework/py/flwr/cli/login/login.py
  framework/py/flwr/cli/utils.py
  framework/py/flwr/common/constant.py
  framework/py/flwr/common/typing.py
  framework/py/flwr/proto/control_pb2.py
  framework/py/flwr/proto/control_pb2.pyi
  framework/py/flwr/server/app.py
  framework/py/flwr/superlink/auth_plugin/noop_auth_plugin.py
  framework/py/flwr/superlink/servicer/control/control_account_auth_interceptor.py
  framework/py/flwr/superlink/servicer/control/control_account_auth_interceptor_test.py
  framework/py/flwr/superlink/servicer/control/control_grpc.py
  framework/py/flwr/superlink/servicer/control/control_servicer.py
  framework/py/flwr/superlink/servicer/control/control_servicer_test.py
Labels: Maintainer, Dynamic Add/Remove SuperNodes

#5973 refactor(framework): Improve `flwr ls` and introduce `flwr list` alias
  framework/py/flwr/cli/app.py
  framework/py/flwr/cli/ls.py
Labels: Maintainer

#5970 docs(intelligence): Add CRC how-to guide
  intelligence/docs/source/_static/signup/api-key-created-dashboard.png
  intelligence/docs/source/_static/signup/api-key-created.png
  intelligence/docs/source/_static/signup/api-key-creation.png
  intelligence/docs/source/_static/signup/api-keys-dashboard.png
  intelligence/docs/source/_static/signup/mgmt-key-created.png
  intelligence/docs/source/_static/signup/mgmt-key-creation.png
  intelligence/docs/source/_static/signup/project-creation.png
  intelligence/docs/source/_static/signup/project-dashboard.png
  intelligence/docs/source/_static/signup/projects-dashboard.png
  intelligence/docs/source/_static/signup/projects.png
  intelligence/docs/source/how-to-use-crc.rst
  intelligence/docs/source/index.rst
Labels: Maintainer
